apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for application's http service
  labels:
    application: mlbparks
    createdBy: template-mlbparks-eap
  name: {{ .Values.application_name }}
spec:
  host: {{ .Values.application_hostname }}
  to:
    kind: Service
    name: {{ .Values.application_name }}
